### ISSUE TITLE
error: user .... leaks permission to update tile .... in parent scene

### ISSUE THREAD

**Issue by tomtec29** [Aedif/move-that-for-you#3]
error: user .... leaks permission to update tile .... in parent scene, when a player wants to move a tile
 
i use foundry vtt 10.291
the black eye (das schwarze auge) 4.1.20 player system
on the forge

best regards
thomas

**Comment by Aedif** [comment]
Are you sure you gave your player the permission to move the tile?

Left-click this button to make it highlighted:

![image](https://user-images.githubusercontent.com/7693704/206790300-96e5b01f-bcc0-4f65-b0e5-2aca6aaa93f7.png)

Right-clicking will give permission to rotate the tile:

![image](https://user-images.githubusercontent.com/7693704/206790379-adafacd7-5576-49de-adeb-120ba0807ce1.png)

Press both left-click and right-click to give permissions to both move and rotate it:

![image](https://user-images.githubusercontent.com/7693704/206790477-21ce0c4f-56e3-4954-b342-63d5f009c701.png)


Also make sure that there is a GM online when the player is attempting to move the tile, otherwise they will be unable to do it.

I tested the module with the following app/game versions and it seemed to work fine:
![image](https://user-images.githubusercontent.com/7693704/206790714-1635a60d-a9f0-4dbd-90cb-281016744c70.png)

**Comment by tomtec29** [comment]
yes i make it like that and the GM is online.
it only works when the player has the assistant GM permission!
with player or  thrustet player permission i got the error.
the permissions are standard.

**Comment by Aedif** [comment]
Seems like this bug was specific to ForgeVTT.

Should be fixed in release [1.4.1](https://github.com/Aedif/move-that-for-you/releases/tag/1.4.1)

**Comment by tomtec29** [comment]
now i dont get the error again and the player can move the tile BUT when i release the mouse button the tile went back to start position!

**Comment by Aedif** [comment]
Did you set any "boundaries" on the current scene? Press Shift+B and clear the boundaries just in case:
![image](https://user-images.githubusercontent.com/7693704/208204083-921ff149-e697-43c9-b340-66d98f80b54d.png)

**Comment by tomtec29** [comment]
this was the problem! thx
